/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Double.parseDouble;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Umesh Punshi
 */

public class ContactEditorUI extends javax.swing.JFrame{

    /**
     * Creates new form ContactEditorUI
     */
    public ContactEditorUI()  {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        PrintReceipt.addActionListener(new ReceiptPrinter(this));
        ArrayList<String> item = new ArrayList<>();
        ArrayList<String> item_names = new ArrayList<>();
        ArrayList<Double> price = new ArrayList<>();
        String [] items = null;
        String [] items_names = null;
        Double [] prices = null;
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","goldberg2k17");
        String timeStamp = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
        jLabel5.setText("STOCK MANAGEMENT SYSTEM ("+timeStamp+")");
        Statement ps = con.createStatement();
        ResultSet rs = ps.executeQuery("select product_id,product_name,unit_price from product");
        int i=0;
        while(rs.next())
        {
            item.add(rs.getString(1));
            item_names.add(rs.getString(2));
            price.add(rs.getDouble(3));
        }
        items = new String[item.size()];
        items_names = new String[item_names.size()];
        prices = new Double[price.size()];
        while(i < items.length)
        {
            items[i]=item.get(i);
            items_names[i]=item_names.get(i);
            prices[i]=price.get(i);
            i++;
        }
        rs = ps.executeQuery("select bill_id from bill where rownum=1 order by bill_id desc");
        rs.next();
        BillNo.setText(Integer.toString(rs.getInt(1)+1));
        BillDate.setText(timeStamp);
        }
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SupplierAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        ProductCode.setModel(new javax.swing.DefaultComboBoxModel(items));
        ProductName.setModel(new javax.swing.DefaultComboBoxModel(items_names));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BillNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BillDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AccName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CustName = new javax.swing.JTextField();
        FetchExisting = new javax.swing.JButton();
        TotalAmountWindow = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        Amount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        M_Stock = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ProductCode = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        ProductName = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        Qty = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        UPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TotalPrice = new javax.swing.JTextField();
        AddIntoList = new javax.swing.JButton();
        F_Pcode = new javax.swing.JTextField();
        F_PName = new javax.swing.JTextField();
        Fetch = new javax.swing.JButton();
        notAvailable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Items = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel12 = new javax.swing.JLabel();
        BillAmount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CashReceived = new javax.swing.JTextField();
        Balance = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        BillConfirmation = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        PrintReceipt = new javax.swing.JButton();
        Preview = new javax.swing.JButton();
        CreateNew = new javax.swing.JButton();
        DeleteItem = new javax.swing.JButton();
        ConfirmBill = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(230, 242, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setToolTipText("Name");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 58, 58));
        jLabel1.setText("Bill No:");

        BillNo.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        BillNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 58, 58));
        jLabel2.setText("Bill Date:");

        BillDate.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        BillDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillDateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(61, 58, 58));
        jLabel3.setText("Account Name:");

        AccName.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        AccName.setText("CASH IN HAND");
        AccName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 58, 58));
        jLabel4.setText("Customer Name:");

        CustName.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        CustName.setText("REGULAR CUSTOMER");
        CustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustNameActionPerformed(evt);
            }
        });

        FetchExisting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        FetchExisting.setForeground(new java.awt.Color(0, 102, 102));
        FetchExisting.setText("Fetch Existing Bill");
        FetchExisting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FetchExistingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BillDate, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(136, 136, 136)
                                .addComponent(BillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(168, 168, 168)
                        .addComponent(FetchExisting, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(48, 48, 48)
                            .addComponent(AccName, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FetchExisting, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BillDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 120, 1122, 262);

        TotalAmountWindow.setBackground(new java.awt.Color(255, 204, 204));
        TotalAmountWindow.setForeground(new java.awt.Color(255, 204, 204));
        TotalAmountWindow.setTitle("Grand Total / Net Receivable");
        TotalAmountWindow.setVisible(true);

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setForeground(new java.awt.Color(255, 204, 204));

        Amount.setBackground(new java.awt.Color(255, 204, 204));
        Amount.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        Amount.setForeground(new java.awt.Color(255, 0, 0));
        Amount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Amount.setText("0.00");
        Amount.setToolTipText("");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(Amount)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout TotalAmountWindowLayout = new javax.swing.GroupLayout(TotalAmountWindow.getContentPane());
        TotalAmountWindow.getContentPane().setLayout(TotalAmountWindowLayout);
        TotalAmountWindowLayout.setHorizontalGroup(
            TotalAmountWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TotalAmountWindowLayout.setVerticalGroup(
            TotalAmountWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(TotalAmountWindow);
        TotalAmountWindow.setBounds(1160, 120, 470, 270);

        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        M_Stock.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        M_Stock.setForeground(new java.awt.Color(255, 0, 0));
        M_Stock.setText("Manage Stock");
        M_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_StockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(M_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(M_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1640, 94);

        jPanel2.setBackground(new java.awt.Color(230, 242, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setToolTipText("");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(61, 58, 58));
        jLabel7.setText("Product Details");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
        );

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(61, 58, 58));
        jLabel6.setText("Qty:");

        ProductCode.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        ProductCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductCodeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(61, 58, 58));
        jLabel8.setText("Product Code:");

        ProductName.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        ProductName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(61, 58, 58));
        jLabel9.setText("Product Name:");

        Qty.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        Qty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qty.setText("1.0");
        Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(61, 58, 58));
        jLabel10.setText("Unit Price");

        UPrice.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        UPrice.setForeground(new java.awt.Color(255, 0, 51));
        UPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UPrice.setText("0.00");
        UPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPriceActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(61, 58, 58));
        jLabel11.setText("Total");

        TotalPrice.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        TotalPrice.setForeground(new java.awt.Color(255, 0, 51));
        TotalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalPrice.setText("0.00");
        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        AddIntoList.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        AddIntoList.setForeground(new java.awt.Color(255, 0, 0));
        AddIntoList.setText("Add");
        AddIntoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIntoListActionPerformed(evt);
            }
        });

        F_Pcode.setBackground(new java.awt.Color(255, 204, 204));
        F_Pcode.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        F_Pcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_PcodeActionPerformed(evt);
            }
        });

        F_PName.setBackground(new java.awt.Color(204, 255, 204));
        F_PName.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        F_PName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_PNameActionPerformed(evt);
            }
        });

        Fetch.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        Fetch.setForeground(new java.awt.Color(255, 0, 0));
        Fetch.setText("Fetch");
        Fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FetchActionPerformed(evt);
            }
        });

        notAvailable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        notAvailable.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_Pcode, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(ProductName, 0, 545, Short.MAX_VALUE)
                            .addComponent(F_PName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(11, 11, 11)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notAvailable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Fetch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddIntoList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addGap(932, 932, 932)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(AddIntoList, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fetch, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_PName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_Pcode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(notAvailable))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jLabel8)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );

        Items.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Items.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Items.setForeground(new java.awt.Color(255, 0, 51));
        Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Product Code", "Product Name", "Qty", "Price"
            }
        ));
        Items.setAlignmentY(10.0F);
        Items.setRowHeight(20);
        jScrollPane1.setViewportView(Items);

        jInternalFrame1.setVisible(true);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Bill Amount:");

        BillAmount.setBackground(new java.awt.Color(204, 255, 204));
        BillAmount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BillAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        BillAmount.setText("0.00");
        BillAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillAmountActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Cash Received:");

        CashReceived.setBackground(new java.awt.Color(204, 255, 204));
        CashReceived.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CashReceived.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CashReceived.setText("0.00");
        CashReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashReceivedActionPerformed(evt);
            }
        });

        Balance.setBackground(new java.awt.Color(255, 204, 204));
        Balance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Balance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Balance.setText("0.00");
        Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Cash Balance:");

        BillConfirmation.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        BillConfirmation.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BillAmount)
                            .addComponent(Balance, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CashReceived)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 76, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BillConfirmation)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addComponent(CashReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BillConfirmation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jInternalFrame1)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInternalFrame1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(232, 232, 232))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 400, 1610, 500);

        jPanel7.setBackground(new java.awt.Color(230, 242, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setForeground(new java.awt.Color(204, 204, 255));

        PrintReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PrintReceipt.setForeground(new java.awt.Color(255, 51, 0));
        PrintReceipt.setText("Print Receipt");
        PrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintReceiptActionPerformed(evt);
            }
        });

        Preview.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Preview.setForeground(new java.awt.Color(255, 51, 204));
        Preview.setText("Preview");
        Preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewActionPerformed(evt);
            }
        });

        CreateNew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CreateNew.setForeground(new java.awt.Color(51, 51, 255));
        CreateNew.setText("Create New");
        CreateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewActionPerformed(evt);
            }
        });

        DeleteItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteItem.setForeground(new java.awt.Color(0, 51, 51));
        DeleteItem.setText("Delete Item");
        DeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemActionPerformed(evt);
            }
        });

        ConfirmBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ConfirmBill.setForeground(new java.awt.Color(255, 51, 204));
        ConfirmBill.setText("Confirm Bill");
        ConfirmBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBillActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setText("View Journals");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Preview, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmBill, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Preview, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CreateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ConfirmBill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(20, 910, 1610, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustNameActionPerformed

    private void AccNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccNameActionPerformed

    private void BillDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillDateActionPerformed
        
    }//GEN-LAST:event_BillDateActionPerformed

    private void BillNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillNoActionPerformed

    private void ProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductCodeActionPerformed

    private void ProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameActionPerformed

    private void QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtyActionPerformed

    private void UPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UPriceActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void AddIntoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIntoListActionPerformed
        total_amount = total_amount + Double.parseDouble(TotalPrice.getText());
        Amount.setText(Double.toString(total_amount));
        BillAmount.setText(Double.toString(total_amount));
        Balance.setText(Double.toString(total_amount));
        notAvailable.setText("");
        String p1 = F_Pcode.getText();
        String p2 = F_PName.getText();
        String p3 = Qty.getText();
        String p4 = TotalPrice.getText();
        
        Object [] row = {p1,p2,p3,p4};
        
        DefaultTableModel model = (DefaultTableModel) Items.getModel();
        model.addRow(row);
        
        F_Pcode.setText("");
        F_PName.setText("");
        Qty.setText("1.0");
        UPrice.setText("0.00");
        TotalPrice.setText("0.00");
    
    }//GEN-LAST:event_AddIntoListActionPerformed

    private void BillAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillAmountActionPerformed

    private void CashReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashReceivedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashReceivedActionPerformed

    private void BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceActionPerformed

    private void PreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewActionPerformed
       new Preview(this);
    }//GEN-LAST:event_PreviewActionPerformed

    private void CreateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewActionPerformed
        ContactEditorUI.this.setVisible(false);
        new ContactEditorUI().setVisible(true);
    }//GEN-LAST:event_CreateNewActionPerformed

    private void DeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) Items.getModel();
        total_amount = total_amount - Double.parseDouble((String) Items.getModel().getValueAt(Items.getSelectedRow(),3));
        Amount.setText(Double.toString(total_amount));
        BillAmount.setText(Double.toString(total_amount));
        Balance.setText(Double.toString(total_amount));
        model.removeRow(Items.getSelectedRow());
    }//GEN-LAST:event_DeleteItemActionPerformed

    private void FetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FetchActionPerformed
         try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","goldberg2k17");
        PreparedStatement ps = con.prepareStatement("select product_id,product_name,unit_price,available_qty from product where product_id = ?");
        if(F_Pcode.getText().equals(""))
        {
            ps.setString(1, ProductCode.getSelectedItem().toString());
        }
        else
        {
           ps.setString(1, F_Pcode.getText());
        }
        
        ResultSet rs = ps.executeQuery();
        
        rs.next();
        F_Pcode.setText(rs.getString(1));
        F_PName.setText(rs.getString(2));
        ProductName.setSelectedItem(rs.getString(2));
        UPrice.setText(Double.toString(rs.getDouble(3)));
        double qty = rs.getDouble(4);
        if(qty < Double.parseDouble(Qty.getText()))
        {
            notAvailable.setText("Sorry! Requested Quantity is not in stock.");
            Qty.setText(Double.toString(qty));
        }
        double total = Double.parseDouble(Qty.getText()) * Double.parseDouble(UPrice.getText());
        TotalPrice.setText(Double.toString(total));
        }
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SupplierAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FetchActionPerformed

    private void F_PcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_PcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_PcodeActionPerformed

    private void M_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_StockActionPerformed
        // TODO add your handling code here:
        StockManagement frame2 = new StockManagement();
        ContactEditorUI.this.setVisible(false); // TODO add your handling code here:
        frame2.setVisible(true);   
    }//GEN-LAST:event_M_StockActionPerformed

    private void ConfirmBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBillActionPerformed
        Balance.setText(Double.toString(total_amount - Double.parseDouble(CashReceived.getText())));
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","goldberg2k17");
            PreparedStatement ps = con.prepareStatement("insert into bill values (?,?,?,?,?,?)");
            ps.setString(1, BillNo.getText());
            ps.setString(2, BillDate.getText());
            if(CustName.getText().equals("REGULAR CUSTOMER"))
            {
                ps.setDouble(3, 101);
            }
            else
            {
                PreparedStatement ps2 = con.prepareStatement("select cust_id from customer where rownum=1 order by cust_id desc");
                ResultSet rs = ps2.executeQuery();
                rs.next();
                ps2 = con.prepareStatement("insert into customer values(?,?)");
                ps2.setDouble(1, rs.getDouble(1)+1);
                ps2.setString(2, CustName.getText());
                ps2.executeQuery();
                ps.setDouble(3, rs.getDouble(1)+1);
            }
            if(AccName.getText().equals("CASH IN HAND"))
            {
                ps.setString(4, "2001");
            }
            ps.setDouble(5, total_amount);
            ps.setDouble(6,Double.parseDouble(CashReceived.getText()));
            ps.executeUpdate();
            
            for(int i=0;i<Items.getRowCount()-1;i++)
            {
            ps = con.prepareStatement("insert into billdetails values (?,?,?,?)");
            PreparedStatement ps1 = con.prepareStatement("select available_qty from product where product_id = ?");
            
            ps.setString(1, BillNo.getText());
            ps.setString(2, (Items.getModel().getValueAt(i+1, 0)).toString());
            ps1.setString(1, (Items.getModel().getValueAt(i+1, 0)).toString());
            ResultSet rs = ps1.executeQuery();
            rs.next();
            double available = rs.getDouble(1);
            ps.setDouble(3,Double.parseDouble((Items.getModel().getValueAt(i+1, 2)).toString())) ;
            double remaining = available - parseDouble((Items.getModel().getValueAt(i+1, 2)).toString());
            PreparedStatement ps2 = con.prepareStatement("update product set available_qty = ? where product_id = ?");
            ps2.setDouble(1, remaining);
            ps2.setString(2, (Items.getModel().getValueAt(i+1, 0)).toString());
            ps.setDouble(4,Double.parseDouble((Items.getModel().getValueAt(i+1, 3)).toString())) ;
            ps.executeUpdate();
            ps2.executeUpdate();
            }
            BillConfirmation.setText("Bill Confirmed!");
            
        
        }
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SupplierAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConfirmBillActionPerformed

    private void F_PNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_PNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_PNameActionPerformed

    private void FetchExistingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FetchExistingActionPerformed
        FetchExisting frame2 = new FetchExisting(BillNo.getText());
        frame2.setVisible(true);
    }//GEN-LAST:event_FetchExistingActionPerformed

    private void PrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintReceiptActionPerformed
        
    }//GEN-LAST:event_PrintReceiptActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        ViewJournals frame100 = new ViewJournals();
        ContactEditorUI.this.setVisible(false);
        frame100.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactEditorUI().setVisible(true);
            }
        });
                }
    double total_amount= 0;
    String [][] listing = new String [13][4];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AccName;
    private javax.swing.JButton AddIntoList;
    private javax.swing.JLabel Amount;
    public javax.swing.JTextField Balance;
    public javax.swing.JTextField BillAmount;
    private javax.swing.JLabel BillConfirmation;
    public javax.swing.JTextField BillDate;
    public javax.swing.JTextField BillNo;
    public javax.swing.JTextField CashReceived;
    private javax.swing.JButton ConfirmBill;
    private javax.swing.JButton CreateNew;
    public javax.swing.JTextField CustName;
    private javax.swing.JButton DeleteItem;
    private javax.swing.JTextField F_PName;
    private javax.swing.JTextField F_Pcode;
    private javax.swing.JButton Fetch;
    private javax.swing.JButton FetchExisting;
    public javax.swing.JTable Items;
    private javax.swing.JButton M_Stock;
    private javax.swing.JButton Preview;
    private javax.swing.JButton PrintReceipt;
    private javax.swing.JComboBox ProductCode;
    private javax.swing.JComboBox ProductName;
    private javax.swing.JTextField Qty;
    private javax.swing.JInternalFrame TotalAmountWindow;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JTextField UPrice;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel notAvailable;
    // End of variables declaration//GEN-END:variables
}
